### ISSUE TITLE
use git submodules for extensions

### ISSUE THREAD

**Issue by kmindi** [cniska/yii-app#1]
If possible use submodules for extensions to not version the code "twice".

**Comment by cniska** [comment]
Submodules are quite a bit of a hassle so I'd rather not.

**Comment by kmindi** [comment]
I find it easier to update the source code. If you change code then you need a seperate repository to let the submodule refer to of course. But if you don't make changes to the extensions it is as easy as `git submodule add $gitURL app/extension/$extensionName`. (and then one time `git submodule init` and `git submodule update`, which both should be recursive per default since git 1.7 or something)

And then they can be used as before;)

**Comment by cniska** [comment]
Well yes, I see your point, but still I'd like to know which version of each extension that I use in order to assure that they all work together as intended. That's why I'd rather do the work of upgrading each component separately. I hope you understand why I chose to do it like this.

**Comment by kmindi** [comment]
You may checkout a specific tagged commit in a submodule. You are not forced to use the latest changes from a possible unstable master branch.
