### ISSUE TITLE
Index.php refers to the wrong configbuilder file location.

### ISSUE THREAD

**Issue by sitawit** [cniska/yii-app#10]
I clone the latest Yii-App. After I config all things here is what happens.

Warning: require_once(MY_ROOT_PATH\web/../vendor/crisu83/yii-configbuilder/helpers/EnvConfigBuilder.php) [function.require-once]: failed to open stream: No such file or directory in...

Possible cause
index.php refers to EnvConfigBuilder but the file doesn't exist.

Solution
Just update index.php to use ConfigBuilder file and class.

**Comment by cniska** [comment]
Thanks for noticing this.I forgot to push the latest changes, sorry for the inconvenience.
