### ISSUE TITLE
Grunt keeps waiting...

### ISSUE THREAD

**Issue by fierwebdesign** [cniska/yii-app#14]
I managed to follow the installation-procedure up until the running of Grunt. It runs, but gets stuck waiting. I'm waiting several minutes now.

```
grunt
Running "watch" task
Waiting...
```

Because it gives no error I don't know what goes wrong. Is this perhaps a common problem? Should I just have more patience? Is there an installation problem?

**Comment by cniska** [comment]
It's a watcher so you should run it in a screen. In other words it's
working as it should. If you change a js or less file it should compile
automatically while it's running.

**Comment by fierwebdesign** [comment]
The wait task kept waiting. I finished the necessary tasks by running them manually though, so problem solved for now.

**Comment by cniska** [comment]
The watch task is meant to be kept running while you develop to do e.g.
compiling of less files "on the fly".
