### ISSUE TITLE
Console dev and env commands not working

### ISSUE THREAD

**Issue by fierwebdesign** [cniska/yii-app#15]
When installing yii-app, my terminal doesn't accept the yiic command. It only works if I point it to the yiic file in the vendor directory like this:

```
vendor/yiisoft/yii/framework/yiic
```

Then still, however, it does not accept the debug and env commands. I get this message:

```
vendor/yiisoft/yii/framework/yiic env dev
Yii command runner (based on Yii v1.1.13)
Usage: vendor/yiisoft/yii/framework/yiic <command-name> [parameters...]

The following commands are available:
 - message
 - migrate
 - shell
 - webapp

To see individual command help, use the following:
   vendor/yiisoft/yii/framework/yiic help <command-name>
```

How can I make the integration of these commands in the console work?

**Comment by cniska** [comment]
yiic can be ran from the app folder, did you try that?

On Tue, May 7, 2013 at 11:55 AM, fierwebdesign notifications@github.comwrote:

> When installing yii-app, my terminal doesn't accept the yiic command. It
> only works if I point it to the yiic file in the vendor directory like this:
> 
> vendor/yiisoft/yii/framework/yiic
> 
> Then still, however, it does not accept the debug and env commands. I get
> this message:
> 
> vendor/yiisoft/yii/framework/yiic env dev
> Yii command runner (based on Yii v1.1.13)
> Usage: vendor/yiisoft/yii/framework/yiic <command-name> [parameters...]
> 
> The following commands are available:
> - message
> - migrate
> - shell
> - webapp
> 
> To see individual command help, use the following:
>    vendor/yiisoft/yii/framework/yiic help <command-name>
> 
> How can I make the integration of these commands in the console work?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Crisu83/yii-app/issues/15
> .

## 

Best regards,
Christoffer Niska
Phone +358 500 980 565
E-mail ChristofferNiska@gmail.com

**Comment by rscorer** [comment]
Followed your install steps as written. Only changes made to access my DB.

```
$ ./app/yiic env dev
exception 'CException' with message 'Alias "vendor.crisu83.yii-configbuilder.commands.EnvCommand" is invalid. Make sure it points to an existing PHP file and the file is readable.' in /Library/WebServer/client/vendor/yiisoft/yii/framework/YiiBase.php:316
Stack trace:
#0 /Library/WebServer/client/vendor/yiisoft/yii/framework/YiiBase.php(196): YiiBase::import('vendor.crisu83....', true)
...
```

Any hint? Thx

PS File exists:: 

```
$ file vendor/crisu83/yii-configbuilder/commands/EnvCommand.php 
vendor/crisu83/yii-configbuilder/commands/EnvCommand.php: PHP script, ASCII text
$ 
```

**Comment by cniska** [comment]
I have exchanged the configbuilder extension for my new consoletools extension so this issue should be resolved now.
