### ISSUE TITLE
Gii not working

### ISSUE THREAD

**Issue by gb5256** [cniska/yii-app#16]
I have trouble in getting Gii of Bootstrap to work.
Within yiistrap, you say that there is a special Gii version and you also show how to enable it.
But those methods are not working (or I am too dumb) with yii-app.
What ever I do, it keeps using the default gii templates

Any ideas?
gb5256

---

EDIT: Just saw that the yiistrap itself (standalone extension version) does contain a gii folder within the extension. But this folder is not in the yiistrap coming via yii-app.

**Comment by cniska** [comment]
This has already been fixed, yii-app was using an older version of yiistrap.
