### ISSUE TITLE
My  application is giving me  raw html  no bootstrap

### ISSUE THREAD

**Issue by alegbebomby** [cniska/yii-app#18]
i have installed stalled everything .. grunt is "waiting"
i downloaded all the extension and put them in a  vendor folder like  this

![sanap](https://f.cloud.github.com/assets/1929174/830771/de9ebf1a-f173-11e2-8c25-3d7668d6cfc0.PNG)
![sana](https://f.cloud.github.com/assets/1929174/830774/17d348aa-f174-11e2-9335-25610e13baee.PNG)

and i changed my composer.json like this

{
    "name": "/yii-app",
    "description": "A great way to start building your web application with Yii PHP framework.",
    "keywords": ["yii", "application"],
    "homepage": "https://github.com/Crisu83/yii-app",
    "type": "library",
    "license": "BSD-3-Clause",
    "authors": [
        {
            "name": "Christoffer Niska",
            "email": "christoffer.niska@gmail.com",
            "homepage": "http://www.cniska.net"
        }
    ],
    "repositories": [
        {
            "type": "composer",
            "url": "http://packages.phundament.com"
        }
    ],
    "minimum-stability": "dev",
    "require": {
        "php": ">=5.3.2",
        "yii": "1.1.13",
        "yii-auth": "dev-master",
        "yii-image": "dev-master",
        "yii-configbuilder": "dev-master",
        "yii-debug": "dev-master",
        "yii-formatter": "dev-master",
        "yii-multilingual": "dev-master",
        "yii-seo": "dev-master",
        "yii-debug-toolbar": "dev-master",
        "yii-emailer": "dev-master",
        "yiipassword": "dev-master",
        "yiistrap": "dev-master",
        "yiiwheels": "dev-master"
    },
    "autoload": {
        "psr-0": {
            "config": "./app"
        }
    }
}

so i dont know what is wrong!! pls  help

**Comment by cniska** [comment]
Try updating and see if that solves your issue.
