### ISSUE TITLE
Bug in documentation

### ISSUE THREAD

**Issue by mtangoo** [cniska/yii-app#19]
In installing from composer you have written: "composer create-project yii-app [APP-NAME]"

It is supposed to be:
composer create-project crisu83/yii-app [APP-NAME]

It have eaten my good time to figure out the    "[InvalidArgumentException]  Could not find package yii-app with stability stable." Error!

**Comment by cniska** [comment]
I have corrected the docs. Thanks for noticing this.

**Comment by mtangoo** [comment]
great!
