### ISSUE TITLE
Infinite *.less requests

### ISSUE THREAD

**Issue by mertsalik** [cniska/yii-app#2]
.less extensioned file requests are looping forever.

Running on Xampp server
Installed all requirrements (node.js for less) and less configuration is setted as 'client' as default.

![yii-app_bug](https://f.cloud.github.com/assets/652489/91120/6b5f1d38-6591-11e2-8cea-0f8269003ea4.png)

**Comment by cniska** [comment]
I'll fix this tonight. Sorry about the inconvenience.

**Comment by SepuWeb** [comment]
Same problem, just download last version 2 minute ago.

**Comment by jneto81** [comment]
hello, 
using 'watch' => false,  solve me the issue. 

But i don't know if we need and when we need to use  watch => true

**Comment by SepuWeb** [comment]
It works! Thank you!

**Comment by mertsalik** [comment]
Thank you, jneto81.
