### ISSUE TITLE
Yii-app with yii-auth problem

### ISSUE THREAD

**Issue by almix** [cniska/yii-app#28]
When I add in config components:

```
'authManager' => array(
          'behaviors' => array(
            'auth' => array(
              'class' => 'vendor.crisu83.yii-auth.components.AuthBehavior',
            ),
          ),
        ),
        'user' => array(
          'class' => 'vendor.crisu83.yii-auth.components.AuthWebUser',
          'admins' => array('admin', 'foo', 'bar'), // users with full access
        ),
```

then at all pages it shows the error:

**Property "WebUser.admins" is not defined.**

**Comment by almix** [comment]
I tuned it, was my mistake

**Comment by ezequieltejada** [comment]
Hi, Sorry to bring back this question, but I didn't know where to ask.

I created a new yii-app project with composer, and I want to integrate yii-auth with the application but I cannot find a guide to do it, could you help me please?

Thanks.

**Comment by cniska** [comment]
Unfortunately there is no guide to this, but you should be able to install it using the readme included in Auth.
