### ISSUE TITLE
index.php is missing

### ISSUE THREAD

**Issue by maxi032** [cniska/yii-app#29]
I tried to install it according to your instructions but index.php is missing. Any ideea why?

**Comment by cniska** [comment]
You forgot to run the environment command which copies the environment specific files, index.php is one of those files.

**Comment by themanufactory** [comment]
i have the same issue as i can't run the yiic commend, even when i am in the app directory. also tried to run yiic.bat environment dev, but no go.

**Comment by cvanderlinden** [comment]
I think I see what happened here, in the documentation it seems like there are two setup options, "Set-up" and then "Set-up Using Vagrant (Optional)"

I think people might be forgetting to do the first steps first and then the vagrant options after? Is this correct?

**Comment by gb5256** [comment]
no, you only need to do the Vagrant part if you use Vagrant.
Do you use it?

**Comment by iurquiza** [comment]
@gb5256 @cvanderlinden 
You still have to run 'yiic environment dev' even if you use vagrant as the 'console' directory does not exist in the current git branch. The 
'run database migrations'
'enable the development environment'
sections of the bootstrap.sh script will not work.
You can try changing 'console' to 'app' in the bootstrap.sh script, and see if that works.

**Comment by asugrad** [comment]
I struggled with this too at first. Here is what I did to get it running. I used the Vagrant approach. Follow Crisu83's instructions to get Vagrant running. Then, in Terminal, change directory to the 'app' directory: cd app. Then run './yiic environment dev'. That should create all the proper files for you, including the 'index.php' file.

**Comment by cniska** [comment]
Closing this since the problem was (most likely) that the reporter forgot to run the environment command.
