### ISSUE TITLE
Email

### ISSUE THREAD

**Issue by fierwebdesign** [cniska/yii-app#3]
Hi Chris,

I'm thankfully using some of your yii-extensions. Thank you for your great contribution!
I have a question about this one. The e-mail extension u use, is there any manual for it? Or at least a short description of how to begin using it?

Thanks in advance.
Greetings,
Laurens

**Comment by cniska** [comment]
Hey,

It's brand new I wrote it yesterday at work. I'm going to write a readme
for it within a few days. However I can give you a quick walk through.

So the first thing you need to do is add the Emailer component to you app
config. Then you can use it through Yii::app()->email or attach the
EmailBehavior to your controller and use it through that. I'd suggest that
you take a look at the code in the Emailer class.

If you want to use templates you need to define them in your app config.
Here's a quick example:

'templates'=>array(
  'foo'=>array(
   'subject'=>'Foo',
   'view'=>'foo', // refers to a view in views/email
  ),
),

Let me know if you further questions.

-Christoffer
