### ISSUE TITLE
Vagrantfile file permissions

### ISSUE THREAD

**Issue by iurquiza** [cniska/yii-app#39]
Having the fmode as 666 in the following line:
config.vm.synced_folder ".", "/vagrant", :mount_options => ["dmode=777", "fmode=666"]
will prevent running the yiic script since it wont be executable, also you wont be allowed to change them using chmod within the vagrant shell.
I was going to suggest using 755, but that wont work either because apache is not able to write to the assets directory. 777 is probably the best for development using vagrant due to the mismatch of user between the host and guest os's.

**Comment by cniska** [comment]
This is not true, since runinng `composer install` after ssh:ing to your vm will fix that permission issue by a post-install-hook.

**Comment by cniska** [comment]
Closing

**Comment by iurquiza** [comment]
Thanks @Crisus83, you might want to mention that in the README.md. It will helps some of us noobs get the app up and running faster.

**Comment by cniska** [comment]
As soon as I have time I will, you could also consider doing a PR for this. I'm currently working on a new application stack that scales better than yii-app does.
