### ISSUE TITLE
provision/bootstrap.sh

### ISSUE THREAD

**Issue by iurquiza** [cniska/yii-app#41]
I am not sure if I am the only one experiencing this, but 'vagrant up' will hang forever when it is ran for the first time. I've had to kill the process, and run it again. I believe it has to do with the fact that some items in the bootstrap.sh script have an interactive installation. I am not sure how that can be handle during 'vagrant up', but the way I've gotten around this issue is to comment out 
config.vm.provision "shell", :path => "provision/bootstrap.sh"
from the Vagrant files, and run the bootstrap.sh script within the vagrant shell after typing 'vagrant ssh'.
Note that you will have to change "fmode=666" to "fmode=777" or "fmode=755" otherwise the shell script wont be executable.

Note that the interactive part is related to "sendmail", so maybe commenting it out might help avoid 'vagrant up' hanging.

**Comment by cniska** [comment]
This is a weird issue, however you seem to be the only one experiencing it so I'm closing this as I haven't encountered this issue myself.
