### ISSUE TITLE
include(APasswordBehavior.php): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by gb5256** [cniska/yii-app#43]
Just ran the composer update and now yii app throws this message.
Do not know if this is related to to yii app, or to the phpnode/password.
I do use "phpnode/yiipassword": "dev-master"

gb5256

**Comment by cniska** [comment]
Composer probably pulled the latest version of Yii Password and they changed some class names, sorry for the inconvenience but you need to either go back to an older version of Yii Password or change the class name in all the necessary files.
