### ISSUE TITLE
EnvConfigBuilder in dev/index entry scripts breaks env switching

### ISSUE THREAD

**Issue by tom--** [cniska/yii-app#6]
Changes in [01923c5](https://github.com/Crisu83/yii-app/commit/01923c5749ab17f22f9ac191f0fec9b2b37dad48) mean that switching between index.php and dev.php in the browser no longer switches configs. In order to disable the `YiiDebugToolbar` you must run the `yiic env` **and** switch entry scripts.

**Comment by cniska** [comment]
The transition to EnvConfigBuilder is still a bit in the works. I removed the dev.php entry script because didn't see the need for it anymore. It was a bit bad practice anyway because it had to be removed in the production environment.
