### ISSUE TITLE
`EnvConfigBuilder` yicc command and `build()` out of sync

### ISSUE THREAD

**Issue by tom--** [cniska/yii-app#7]
Changes in [01923c5](https://github.com/Crisu83/yii-app/commit/01923c5749ab17f22f9ac191f0fec9b2b37dad48) cause entry scripts to look for the env global switch in `application.runtime` while the `yiic env` command is still writing to `application.config.environments`

**Comment by cniska** [comment]
The environment file (containing the name of the active environment) is by default saved under runtime while the environmental specific configurations are by default saved under config/environments. I don't see how this is an issue so I'm closing this issue.
