### ISSUE TITLE
Can't click link on navbar?

### ISSUE THREAD

**Issue by santhika29** [cniska/yii-app#8]
## I've already install Yii-App without any problem. But when I go to the main web page I can't click on the link to other page. For example, login page. It is there in the page but when I click it the browser don't go to that page but the URL itself is fine when I type in the URL directly it's ok. I don't see any error on browser's console. i already try in chrome and firefox and no luck.

i already got the trouble for that error above i descript. i think that because this code
"<?php app()->bootstrap->registerAllScripts(); ?>"
link on the navbar will work if i delete that line but the dropdown menu will not work. any suggestion? 

and i got error message like in the image i uploaded.
![error message](https://f.cloud.github.com/assets/3783522/296445/826e2f18-94f9-11e2-9c10-d0cc06a40cc0.png)

Any idea what could be the problem. Thanks.

**Comment by cniska** [comment]
I've fixed this issue, it's actually an issue in the yiistrap extension. Please update to the head revision of yiistrap and it should fix this issue.

**Comment by cniska** [comment]
The other issue is my bad. I'll fix it when I have time, sorry about that.
