### ISSUE TITLE
error 500 in update

### ISSUE THREAD

**Issue by santhika29** [cniska/yii-app#9]
thanks for the fix in previous bug.
i think i got another one.
when i want to updated a record on my db i always got this message

![error 1](https://f.cloud.github.com/assets/3783522/301212/9edacc08-95c4-11e2-8d40-e19ec5ffdc25.png)
 i already try and error several ways but no luck..

any suggestion?

when i use the normal yii i never got that message...

thanks

**Comment by cniska** [comment]
Without knowing more I have to say that I have no clue what could the the issue behind this.
